context:
  version: "1.1.3"

package:
  name: ffbidx
  version: ${{ version }}

source:
  url: https://github.com/paulscherrerinstitute/fast-feedback-indexer/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a71db9e076630f409b7329b85ee70870d124f3008de32f60da561bf3955bcc3b

build:
  number: 3
  skip:
    - not linux64
    - cuda_compiler_version in ["None", "11.8"]

requirements:
  build:
    - ${{ compiler('cuda') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - meson
    - pkg-config
  host:
    - eigen
    - python
    - numpy
  run:
    - python
    - cuda-runtime

tests:
  - python:
      imports:
        - ffbidx
      pip_check: true

about:
  homepage: https://github.com/paulscherrerinstitute/fast-feedback-indexer
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: Fast feedback indexer library with python module for xray crystallography
  description: |
    Fast feedback indexer library with the python module for xray crystallography.
    Paper reference: https://doi.org/10.1107/S1600576724003182
    Code repository: https://github.com/paulscherrerinstitute/fast-feedback-indexer
    dev_url: https://github.com/paulscherrerinstitute/fast-feedback-indexer
    doc_url: https://github.com/paulscherrerinstitute/fast-feedback-indexer/blob/main/python/README.md

extra:
  recipe-maintainers:
    - dagewa
    - hcstadler
